### ISSUE TITLE
部署完成后msg:close

### ISSUE THREAD

**Issue by Song-Xin233** [HammCn/BBBUG-API#1]
访问站点/api返回json:
"code":200,"msg":"close","data":{"success":0,"data": ... ... ...

访问地址
http://ssxx.site:30086/api

部署环境
Windows server 2019标准版
apache2.4
PHP7.4
MySQL8.0
redis 3.0

**Comment by HammCn** [comment]
查看api下BaseCtroller.php中和Index.php中对应方法，搜索//Fuck放开对应的注释代码即可

**Comment by Song-Xin233** [comment]
very thx!
成功了！
